name = "ZeroDEBMs"
uuid = "ad5a52e4-ee06-4f3f-ac2d-a72b939a0981"
authors = ["Maximilian Gelbrecht <maximilian.gelbrecht@posteo.de> and contributors"]
version = "0.2.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
